### ISSUE TITLE
Deletes votes sometimes from the current motion.

### ISSUE THREAD

**Issue by giantsquad** [evaera/Votum#36]

**Comment by evaera** [comment]
please provide reproduction steps!

**Comment by giantsquad** [comment]
> please provide reproduction steps!

sorry, I don't get what you mean by this.

**Comment by evaera** [comment]
steps to reproduce the error?

**Comment by giantsquad** [comment]
I create a motion like normal
Some people vote
And then occassionally, one person's vote doesn't show up on the votum embeds after a few votes
And they have to revote

**Comment by evaera** [comment]
I believe this is fixed. Reopen if not!
