### ISSUE TITLE
Ability to Add and Remove Users from Weighted Voting by Command

### ISSUE THREAD

**Issue by stephenmonk** [evaera/Votum#42]
It would be really nice if we could add a new user to the Weighting by command.  (!config add.weight 2312931929321912 3) and remove them from the Weighting in similar fashion !config remove.weight 12312312312312)

Where %1 is the userid and %2 is the vote total.

That will mean we can script that process more easily and removes the headache of maintaining a JSON file.

**Comment by evaera** [comment]
This should be a lot easier with the web panel

**Comment by stephenmonk** [comment]
Is it possible to do in the interim via command?  Just parse the JSON field to see if userid is already there and then update, and if not there tag on to the end?  And for remove just find all iterations of the userid and remove.  Obvious not as clean as a nice web interface but eliminates potential errors with passing a long json string in.

**Comment by evaera** [comment]
possible yeah, but I would make it a different command since !config is purely for get/set of static values. Wouldn't want to add custom behavior there

**Comment by stephenmonk** [comment]
Sounds good.  Are the vote weights per council?

**Comment by evaera** [comment]
Yes, they are
