### ISSUE TITLE
Allow proposers to not have to be council members as well.

### ISSUE THREAD

**Issue by stephenmonk** [evaera/Votum#43]
We are looking to have our Server Admins be the only ones who can start a motion, but those users are NOT allowed to be voting council members.  I'd like to remove the restriction that the proposer must also have the council role.  Or at least a way to mark an admin as a non-voting council member.

**Comment by evaera** [comment]
I think the easiest way to do this would be to allow admins to use the !motion command even if they aren't councilors.

**Comment by stephenmonk** [comment]
The admins I have don't actually have admin role in the server.  So it would need the ability for us to define the role to treat as admin.

**Comment by evaera** [comment]
I imagine it working the same way admin commands currently do:

![image](https://user-images.githubusercontent.com/2489210/95393274-4d66db80-08c8-11eb-8924-7de0d7f6c75d.png)
