### ISSUE TITLE
Need to be able to mark a council as weighted or not weighted.

### ISSUE THREAD

**Issue by stephenmonk** [evaera/Votum#44]
We have a Committee that starts the amendment process.  Those people have a role called Committee Member and Council Member.  Their Discord ID's have been assigned weighted votes.  The Committee stars the process and then when approved it JSONs over to the Chamber Floor for deliberation and voting.  We want the weighted voting to ONLY apply in the Chamber Floor, not the committee room.  So maybe an easy fix is to have an allow weighted voting option for the council creation?  And if its checked it uses the JSON and if not it doesn't and assumes 1 for 1.  Obviously it would be great to have separate weights for each council if we wanted...but not a requirement.

**Comment by evaera** [comment]
I don't really understand what you mean... The weighted votes option is already a per-council setting

**Comment by stephenmonk** [comment]
Oh.  Well then my bad!
