### ISSUE TITLE
Deliberation Channel Issues

### ISSUE THREAD

**Issue by stephenmonk** [evaera/Votum#46]
Here is some initial feedback/changes for the Deliberation Channels:
1) If a motion was given a title, that title should make it into the channel as either a description of the channel or as a note in the channel.  Otherwise it just has the motion number.
2) The channel should be made inside of the category that the council lives in, not a new category named the same as the Council name.
3) The channel should inherit permissions from the category it is in.  We allow read-only roles to watch the deliberations.  Or perhaps add a config item for "watcher" that we can give permissions to.
4) The bot does not seem to be listening to votes in the deliberation channel.  Ideally all business could be handled in the deliberation channel for that motion.  (Which would let us have multiple votes going at the same time in the future.)

**Comment by evaera** [comment]
Closing as 1-3 have been implemented
